name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

on:
  pull_request:
  push:
    branches: ['main']
  release:
    types:
      - published

jobs:

  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check code formatting
        run: ./sbt check

  compile:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17']
        scala: ['2.13.10', '3.2.2']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Compile sources
        run: ./sbt ++${{ matrix.scala }}! compile

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17']
        scala: ['2.13.10', '3.2.2']
        platform: ['JVM']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests
        run: ./sbt ++${{ matrix.scala }}! -Dzd.scala.version=${{ matrix.scala }} coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  publishLocal:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check that building packages works
        run: ./sbt +publishLocal

  ci:
    runs-on: ubuntu-22.04
    needs: [lint, compile, test, publishLocal, website]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"

  website:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
      - name: Generate website
        run: ./sbt docs/docusaurusCreateSite

  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Release artifacts
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
